image: node:latest

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

test_job:
  stage: test
  script:
    - npm install -g jest
    - npm install --save-dev @babel/preset-env
    - npm install --save-dev @babel/preset-typescript
    - npm test
  dependencies:
    - build_job

