image: node:latest

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

test_job:
  stage: test
  script:
    - npm install -g jest
    - npm install --save-dev @babel/preset-env
    - npm install --save-dev @babel/preset-typescript
    - npm test
  dependencies:
    - build_job

deploy:
  stage: deploy
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish

