image: node:latest

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

before_script:
  - npm ci --cache node_modules --prefer-offline

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - npm install
    - npm run test

test_job:
  stage: test
  script:
    - echo 
    - npm install
    - npm run test

deploy:
  stage: deploy
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=$NPM_ACCESS_TOKEN">.npmrc
    - npm publish
  only:
    refs:
      - master


